development:
   adapter: mysql
   database: library_development
   username: root
   password: same
   host: localhost
  
test:
   adapter: mysql
   database: library_test
   username: root
   password: same
   host: localhost
   
production:
   adapter: mysql
   database: heroku_46b7c4ff6db7df3
   username: bce10f161d3e23
   password: c54c2da0
   host: us-cdbr-iron-east-03.cleardb.net